### ISSUE TITLE
Rgb images have different resolutions with depth images

### ISSUE THREAD

**Issue by lijie2160** [RaymondWang987/NVDS#5]
Thank you for your good job.
Rgb images have different resolutions with depth images， If I want to align the resolution of two images, do I simply resize them?

**Comment by RaymondWang987** [comment]
> Thank you for your good job.
> Rgb images have different resolutions with depth images， If I want to align the resolution of two images, do I simply resize them?

Thanks for your attention to our work. In most cases, simple resizing operations can be adopted as a common practice, if your RGB and depth are strictly corresponding (for the totally same image). I don't know your detailed situation or any specific question in our code. For example, a special case might be: if you want to significantly improve the resolution of depth maps (e.g., from 224 to 1080 or higher), simple resizing could cause some blurs. If that is unacceptable in your situation, you can adopt some depth refinement or super-resolution tools for up-sampling.

**Comment by lijie2160** [comment]
@RaymondWang987 Thank you for your reply. Do I need to retrain the model if I want the resolution of the output depth map to be exactly the same as the rgb image?

**Comment by RaymondWang987** [comment]
> @RaymondWang987 Thank you for your reply. Do I need to retrain the model if I want the resolution of the output depth map to be exactly the same as the rgb image?

For most depth models (e.g., Midas, DPT, or our NVDS), the resolutions of the input RGB image (e.g., inputing $384\times384\times3$) and the predicted depth (e.g., predicting $384\times384\times1$) are the same. In the training stage, input images are resized or cropped to certain resolutions to reduce the computational costs (e.g., GPU memory). In the inference stage, to maintain the best performance, the input images are resized to similar resolutions as the training stage (e.g., $896\times384\times3$, maintaining the aspect ratio of raw images). You can also use the raw resolutions of input images (e.g., $1880\times800$) for inference and the outputs will also be $1880\times800$. 

Overall, the models' input and output are in the same resolution. It depends on the specific resolution used for inference. Many models are robust to the resolution changes because training by large-scale datasets or data augmentations. You can directly infer with raw resolutions. If your model is not sufficiently robust to this problem, you can try to train the model with higher resolutions (but also higher training costs) or with data augmentations (e.g., varied resolutions or random cropping).
