### ISSUE TITLE
Potential Bug in inference: min_fwd < min_fwd

### ISSUE THREAD

**Issue by ray8828** [RaymondWang987/NVDS#7]
Hi, thanks for sharing this great work, i found something strange in the inference code
https://github.com/RaymondWang987/NVDS/blob/edd98389e19447c7aadccda6fb4b14fb9a59a2d0/infer_NVDS_midas_bi.py#L769

When mixing the results, seems there is a bug, the two min_fwd should be one min_bwd? thanks

**Comment by RaymondWang987** [comment]
> Hi, thanks for sharing this great work, i found something strange in the inference code
> 
> https://github.com/RaymondWang987/NVDS/blob/edd98389e19447c7aadccda6fb4b14fb9a59a2d0/infer_NVDS_midas_bi.py#L769
> 
> When mixing the results, seems there is a bug, the two min_fwd should be one min_bwd? thanks

Hi! Thanks for proposing this problem. I have fixed this issue in `infer_NVDS_midas_bi.py` and `infer_NVDS_dpt_bi.py`. 

We initially do not notice this issue, because in most cases (maybe all of our testing sequences), the stabilization network can produce results that satisfy the following condition and utilize bidirectional inference (average of forward and backward):
```
if min_fwd<dpt_index and min_bwd<dpt_index:
    outputs = (fwpred+bwpred)/2
```

Thus, in most cases, the following code is just ignored without running. It's a protection against an abnormal situation that the stabilization network fails to stabilize a certain testing video or even produces worse (flickering) results than initial depth predictors. In all the experiments of our paper, that situation almost does not happen. Thanks a lot for reminding us and I have fixed this issue in our repo.
```
else:
    if min_fwd<min_bwd:
        outputs = fwpred
    else:
        outputs = bwpred
```
